name: ascent
repo_url:  https://github.com/Alpine-DAV/ascent.git
# This tells azemu to find current branch via a git cmd
repo_branch: <CURRENT>
default_container:  alpinedav/alpinedav/ubuntu-22.04-x86_64
